apiVersion: v1
kind: Service
metadata:
  labels:
    app: csm
  name: csm
spec:
  ports:
  - protocol: TCP
    name: "81"
    port: 81
    targetPort: 81
  selector:
    app: csm
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: csm
  name: csm
spec:
  selector:
    matchLabels:
      app: csm
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csm
    spec:
      #nodeName: devciwknd002
      containers:
      - name: csm
        image: hub.docker.local:5000/bank/csm
        imagePullPolicy: "Always"
        ports:
        - containerPort: 81
        resources:
          limits:
            cpu: "1"
            memory: "1073741824"
          requests:
            cpu: 250m
            memory: "536870912"
      restartPolicy: Always
status: {}
