#kubectl create -f pv-data-mysql-1.yaml -n bank-apps
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-1
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mysql-1
  labels:
    type: local
spec:
  storageClassName: local-storage-1
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/host_mnt/c/mnt/data-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-1
spec:
  storageClassName: local-storage-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
