#kubectl create -f pv-data-mysql-0.yaml -n bank-apps
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-0
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mysql-0
  labels:
    type: local
spec:
  storageClassName: local-storage-0
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/host_mnt/c/mnt/data-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-0
spec:
  storageClassName: local-storage-0
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
